### PR TITLE
consolidate and fold schema in build

### PR DESCRIPTION
**Pull request by andyyu2004**
I've changed `build` always apply `fold_transparent_types` and `consolidate_types` , I don't any reason not to?

This is useful to write a reproducing test case for #56.

### CODE REVIEW

**Comment by avkonst** [comment]
Shall it be builder config? "I've changed build always apply fold_transparent_types and consolidate_types , I don't any reason not to?"

**Comment by andyyu2004** [comment]
I'm not sure, these feel like almost mandatory transformations. Is there any time you wouldn't want this?

**Comment by avkonst** [comment]
fold_transparent_types - not sure about it.... It might be wanted for generated client code readability when aliasing types. ?

**Comment by andyyu2004** [comment]
I don't mind reverting this to make it opt-in. I just need it turned on for tests.

**Comment by avkonst** [comment]
I am not sure either. You can keep it as hard code behavior for now, and maybe we will be able to add it as configurable option. Alternatively it might be we could add special reflectapi attribute to force keeping wrappers in the future.

**Pull request merged**
